[services]
gog = True
egs = True
ea_app = True
ubisoft = True
steam = True

[lutris]
library_ignores = 
migration_version = 14
view_type = list
width = 1807
height = 1080
maximized = True
selected_category = category:all

